---
name: Tests in SageMath

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: sagemath/sagemath:10.8
      options: --user root
    steps:
      - name: Installing Tools
        run: apt-get update && apt-get install -y git make
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Compiling Sigma/FS
        working-directory: ./poc/sigma/poc
        run: make
      - name: Compiling ARC
        working-directory: ./poc
        run: make
      - name: Testing
        working-directory: ./poc
        run: make test
      - name: Generate Test Vectors
        working-directory: ./poc
        run: make vectors
